[connections.postgresql]
dialect = "postgresql"
host = "localhost"
port = "5432"
database = "march_madness"
username = "austinburdette"

[connections.supabase]
SUPABASE_URL = "https://qjvaztljeffutvqxkymb.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqdmF6dGxqZWZmdXR2cXhreW1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTA2MzE5MzQsImV4cCI6MjAyNjIwNzkzNH0.64R0euDNbTGARB7QdClJCseAumuu3eXYfPh40nM-7sw"