[connections.supabase]
SUPABASE_URL = "https://qjvaztljeffutvqxkymb.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqdmF6dGxqZWZmdXR2cXhreW1iIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcxMDYzMTkzNCwiZXhwIjoyMDI2MjA3OTM0fQ.SKy_Di_pYJnuvk-KP5L80WwB7qf2IT7dH9GYmbQNROo"